site_name: Solidworks With FRC
site_url: https://team2854.com
nav:
  - Home: index.md
  - Navigation:
    - Home: navigation/home.md
    - Parts: navigation/part.md
    - Assemblies: navigation/assembly.md
    - Drawings: navigation/drawing.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - toc.follow    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
