site_name: SolidWorks for FRC

# Configuration
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.prune
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - header.autohide
  language: en

  # Dark Mode and Light Mode
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: white 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: black

# Navigation

nav: 
  - Home: index.md
  - CAD Basics: 
    - cad-basics/index.md
    - Part Construction: 
      - Controls and Navigation: cad-basics/part-construction/controls.md
      - Basic Sketching: cad-basics/part-construction/basic-sketching.md
      - 3D Modeling: cad-basics/part-construction/3d-modeling.md
    - Assemblies:
      - Mates: cad-basics/assembly-construction/mates.md
      - Layout Sketching: cad-basics/assembly-construction/layout-sketching.md
  - FRC Design: 
    - frc-design/index.md


markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.mark